'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BulkPanelSettings
    
    '''<summary>
    '''rpFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpFacility As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSettings As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbxBulkProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxBulkProduct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFunction As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxStartParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxStartParameter As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxFinishingParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxFinishingParameter As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkAlwaysUseFinishParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAlwaysUseFinishParameter As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tbxAnticipation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxAnticipation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlAnticipationUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAnticipationUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxAnticipationUpdateFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxAnticipationUpdateFactor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxConversionFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxConversionFactor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlConversionFactorUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConversionFactorUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkUpdateDensityUsingMeter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUpdateDensityUsingMeter As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkUseAverageDensityForTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseAverageDensityForTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tbxDumpTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDumpTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkDisabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisabled As Global.System.Web.UI.WebControls.CheckBox
End Class
