'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AllContainers
    
    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnShowReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrinterFriendly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrinterFriendly As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFilterBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilterBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocation As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProduct As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOwner As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCustomerAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomerAccount As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbxShowDeleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxShowDeleted As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlOrderBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrderBy As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAscDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAscDesc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlDisplayedColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDisplayedColumns As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbxNumberColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxNumberColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLocationColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLocationColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxStatusColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxStatusColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxProductColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxProductColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxOwnerColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxOwnerColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxAccountColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxAccountColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLastTransactionColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLastTransactionColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxEmptyWeightColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxEmptyWeightColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxVolumeColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxVolumeColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxProductWeightColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxProductWeightColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxInServiceColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxInServiceColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLastFilledColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLastFilledColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxBulkProdEpaColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxBulkProdEpaColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxSealNumberColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxSealNumberColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxTypeColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxTypeColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxConditionColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxConditionColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLastChangedColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLastChangedColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxManufacturedColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxManufacturedColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLastInspectedColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLastInspectedColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxPassedInspectionColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPassedInspectionColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxRefillableColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxRefillableColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLastCleanedColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLastCleanedColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxNotesColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxNotesColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxSealBrokenColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxSealBrokenColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxPassedPressureTestColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPassedPressureTestColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxOneWayValvePresentColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxOneWayValvePresentColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxForOrderIdColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxForOrderIdColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxEquipmentColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxEquipmentColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxLastUserIdColumnShown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxLastUserIdColumnShown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxCreatedColumnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxCreatedColumnShow As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxAssignedLotColumnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxAssignedLotColumnShow As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnConfigure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfigure As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSendEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxEmailTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxEmailTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rowAddAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAddAddress As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlAddEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAddEmailAddress As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddEmailAddress As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''litEmailConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmailConfirmation As Global.System.Web.UI.WebControls.Literal
End Class
