'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomLoadQuestions
    
    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ddlBay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBay As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPrePost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrePost As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbxQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbxQuestions As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnAddQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddQuestion As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnRemoveQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveQuestion As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnMoveQuestionUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveQuestionUp As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnMoveQuestionDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveQuestionDown As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbxName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxPostLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPostLoad As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tbxPromptText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxPromptText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlQuestionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuestionType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOwner As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''liURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liURL As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxUrl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''liMinCharsRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMinCharsRequired As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxMinimumCharactersRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxMinimumCharactersRequired As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''liMaxCharsAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMaxCharsAllowed As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxMaximumCharactersAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxMaximumCharactersAllowed As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''liAllowOnlyNumericValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAllowOnlyNumericValues As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkAllowOnlyNumericValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowOnlyNumericValues As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''liTableLookupOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTableLookupOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlTableLookupTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableLookupTableName As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTableLookupFieldName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableLookupFieldName As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbxDisabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxDisabled As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbxParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbxParameters As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnAddParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddParameter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnRemoveParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveParameter As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnMoveParameterUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveParameterUp As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnMoveParameterDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveParameterDown As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tbxParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxParameter As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdateParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateParameter As Global.System.Web.UI.WebControls.Button
End Class
