'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DefaultDeliveryWebTicketSettings
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''PleaseWaitMessagePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleaseWaitMessagePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HiddenButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PleaseWaitPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleaseWaitPopup As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PleaseWaitPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleaseWaitPanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlWebTicketOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWebTicketOwner As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblWebTicketSettingsExist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebTicketSettingsExist As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSaveOwnerWebTicketSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveOwnerWebTicketSettings As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteOwnerWebTicketSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOwnerWebTicketSettings As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkNtepCompliant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNtepCompliant As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkAcresOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAcresOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowApplicationRateOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowApplicationRateOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkUseOriginalOrdersApplicationRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseOriginalOrdersApplicationRate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowApplicatorOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowApplicatorOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDisplayBlendGroupNameAsProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisplayBlendGroupNameAsProductName As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowBulkProductSummaryTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowBulkProductSummaryTotals As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowBulkProductNotesSummaryTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowBulkProductNotesSummaryTotals As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowBulkProductEpaNumberSummaryTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowBulkProductEpaNumberSummaryTotals As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkBranchLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBranchLocation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCarrierId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCarrierId As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentsOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentsOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentProductNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentProductNotes As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentBulkIngredients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentBulkIngredients As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentBulkIngredientNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentBulkIngredientNotes As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentBulkIngredientEpaNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentBulkIngredientEpaNumber As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlShowCompartmentBulkIngredientLotNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShowCompartmentBulkIngredientLotNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkShowCompartmentBulkIngredientLotNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentBulkIngredientLotNumber As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentTotals As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCompartmentLoadedIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentLoadedIndex As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCustomer As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCustomerDestinationNotesOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCustomerDestinationNotesOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowCustomerNotesOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCustomerNotesOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTime As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowDensityOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowDensityOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowDerivedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowDerivedFrom As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowDischargeLocationOnTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowDischargeLocationOnTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDriverName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDriverName As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDriverNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDriverNumber As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmailAddress As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowFacility As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowFertilizerGuaranteedAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowFertilizerGuaranteedAnalysis As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowFertilizerGuaranteedAnalysisByCompartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowFertilizerGuaranteedAnalysisByCompartment As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowFertilizerGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowFertilizerGrade As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlAnalysisDecimalCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAnalysisDecimalCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkShowCompartmentFertilizerGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCompartmentFertilizerGrade As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlGradeAnalysisDecimalCountGreaterThanOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGradeAnalysisDecimalCountGreaterThanOne As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlGradeAnalysisDecimalCountLessThanOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGradeAnalysisDecimalCountLessThanOne As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cbxAnalysisEntriesRoundedDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxAnalysisEntriesRoundedDown As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxAnalysisShowTrailingZeros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxAnalysisShowTrailingZeros As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxHideZeroPercentAnalysisNutrients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxHideZeroPercentAnalysisNutrients As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxShowLoadedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxShowLoadedBy As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowOrderSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowOrderSummary As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowOrderSummaryHistorical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowOrderSummaryHistorical As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOwner As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkProductHazardousMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProductHazardousMaterial As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowProductSummaryTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowProductSummaryTotals As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowProductNotesSummaryTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowProductNotesSummaryTotals As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPurchaseOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPurchaseOrder As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkReleaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReleaseNumber As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowRequestedQuantities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowRequestedQuantities As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowRinseEntries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowRinseEntries As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCustomerLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCustomerLocation As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTotal As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTransport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTransport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkShowTicketTransportTareInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTicketTransportTareInfo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tblTransportTareOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTransportTareOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''rowTransportTareFirstOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTransportTareFirstOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlTransportTareFirstOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportTareFirstOption As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rowTransportTareSecondOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTransportTareSecondOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlTransportTareSecondOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportTareSecondOption As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rowTransportTareThirdOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTransportTareThirdOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlTransportTareThirdOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportTareThirdOption As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cblAdditionalUnitsForTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblAdditionalUnitsForTicket As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''ddlWebTicketDensityMass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWebTicketDensityMass As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlWebTicketDensityVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWebTicketDensityVolume As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnWebTicketDensityAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWebTicketDensityAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lstWebTicketDensityList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstWebTicketDensityList As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnWebTicketDensityRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWebTicketDensityRemove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trWebTicketDensityPrecisionControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trWebTicketDensityPrecisionControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnWebTicketDensityAddWhole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWebTicketDensityAddWhole As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnWebTicketDensityRemoveWhole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWebTicketDensityRemoveWhole As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnWebTicketDensityAddFractional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWebTicketDensityAddFractional As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnWebTicketDensityRemoveFractional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWebTicketDensityRemoveFractional As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlProductGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSaveProductGroupAdditionalUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveProductGroupAdditionalUnits As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cblAdditionalUnitsForProductGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblAdditionalUnitsForProductGroup As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''ddlProductGroupDensityMassUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductGroupDensityMassUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlProductGroupDensityVolumeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductGroupDensityVolumeUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxTicketLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTicketLogo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOwnerMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOwnerMessage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxOwnerDisclaimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOwnerDisclaimer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxBlank1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxBlank1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxBlank2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxBlank2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxBlank3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxBlank3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxTicketAddonURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTicketAddonURL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlDeliveryTicketCustomFieldsAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDeliveryTicketCustomFieldsAssigned As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbxShowAllCustomFieldsOnDeliveryTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxShowAllCustomFieldsOnDeliveryTicket As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblShowCustomFieldsOnDeliveryTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblShowCustomFieldsOnDeliveryTicket As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlCustomPreLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomPreLoadQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbxShowAllCustomPreLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxShowAllCustomPreLoadQuestions As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblShowCustomPreLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblShowCustomPreLoadQuestions As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlCustomPostLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomPostLoadQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbxShowAllCustomPostLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxShowAllCustomPostLoadQuestions As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblShowCustomPostLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblShowCustomPostLoadQuestions As Global.System.Web.UI.WebControls.CheckBoxList
End Class
