'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GeneralSettings
    
    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnSaveGeneralSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveGeneralSettings As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblGeneralSettingsSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeneralSettingsSave As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlGeneralSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGeneralSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlDefaultMassUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDefaultMassUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlDefaultVolumeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDefaultVolumeUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxWebPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxWebPageTitle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxDatabaseChangeEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDatabaseChangeEmailAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxConvertWebPageUrlDomainToRequestedPagesDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxConvertWebPageUrlDomainToRequestedPagesDomain As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxDefaultNewDriversValidForAllAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxDefaultNewDriversValidForAllAccounts As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbxItemTraceabilityEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxItemTraceabilityEnabled As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tbxDaysToKeepEventLogRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDaysToKeepEventLogRecords As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxProxyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxProxyAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxProxyPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxProxyPort As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxActivationAlertEmailRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxActivationAlertEmailRecipients As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlApplicationSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApplicationSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxDatabaseBackupFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDatabaseBackupFolder As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlDatabaseBackupNumberOfSets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDatabaseBackupNumberOfSets As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxDatabaseBackupTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDatabaseBackupTimeout As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxBackupLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxBackupLog As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxBackgroundServicesLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxBackgroundServicesLog As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxEmailServiceLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxEmailServiceLog As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxTankStatusLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTankStatusLog As Global.System.Web.UI.WebControls.TextBox
End Class
