'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Help
    
    '''<summary>
    '''Help control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Help As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divApplicators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divApplicators As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBranches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranches As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCarriers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCarriers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAllCarriersReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllCarriersReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divContainers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divContainerTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divContainerEquipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerEquipment As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divContainerEquipmentTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerEquipmentTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAllContainersReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllContainersReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAllContainerEquipmentReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllContainerEquipmentReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divContainerInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerInventory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCropTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCropTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCustomPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomPages As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAccounts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAccountDestinations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAccountDestinations As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAccountCoupling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAccountCoupling As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAllCustomersReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllCustomersReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDrivers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDrivers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDriversInFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDriversInFacility As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDriversInFacilityHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDriversInFacilityHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAllDriversReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllDriversReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divFacilities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFacilities As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBays As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divStorageLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStorageLocations As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCustomLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomLoadQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTracks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTracks As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divGeneralSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGeneralSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divOrderSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrderSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEmailSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEmailSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAnalysisSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAnalysisSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAccountCouplingSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAccountCouplingSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divReceivingPoSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReceivingPoSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divContainerSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTicketSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTicketSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDefaultDeliveryWebTicketSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDefaultDeliveryWebTicketSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDefaultOrderSummarySettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDefaultOrderSummarySettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDefaultReceivingWebTicketSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDefaultReceivingWebTicketSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDefaultReceivingWebPickTicketSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDefaultReceivingWebPickTicketSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDefaultContainerLabelSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDefaultContainerLabelSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaces As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaceTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaceTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaceItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaceItems As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaceUsageReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaceUsageReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaceAssignOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaceAssignOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaceTicketStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaceTicketStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInterfaceReceivingTicketStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInterfaceReceivingTicketStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInventory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInventoryChangeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInventoryChangeReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInventoryGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInventoryGroups As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPastOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPastOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divOrderList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOrderList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divStagedOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStagedOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divInProgressRecordsHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInProgressRecordsHelp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDeleteOrdersHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteOrdersHelp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divArchiveOrdersHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArchiveOrdersHelp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divArchiveTicketsHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArchiveTicketsHelp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPointOfSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPointOfSale As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divOwners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOwners As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPanels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPanels As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDischargeLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDischargeLocations As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPanelGroupsHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPanelGroupsHelp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPanelBulkProductSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPanelBulkProductSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPanelBulkProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPanelBulkProducts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPanelBulkProductFillLimits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPanelBulkProductFillLimits As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProducts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBulkProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBulkProducts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBulkProductAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBulkProductAnalysis As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divProductAllocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProductAllocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBulkProductAllocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBulkProductAllocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divProductList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProductList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divProductGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProductGroups As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divLots control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLots As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divReceivingPurchaseOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReceivingPurchaseOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPastReceivingPurchaseOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPastReceivingPurchaseOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divReceivingPurchaseOrdersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReceivingPurchaseOrdersList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuppliers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDeleteReceivingPurchaseOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteReceivingPurchaseOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divArchiveReceivingPurchaseOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArchiveReceivingPurchaseOrders As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divArchiveReceivingPurchaseOrderTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArchiveReceivingPurchaseOrderTickets As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divCustomerActivityReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomerActivityReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divReceivingActivityReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReceivingActivityReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divReceipts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReceipts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTrackReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTrackReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEmailReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEmailReports As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEmails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEmails As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divBulkProductUsageReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBulkProductUsageReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divApplicationUsage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divApplicationUsage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divEventLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEventLog As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTankLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTankLevels As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTanks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTanks As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTankAnalysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTankAnalysis As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTankGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTankGroups As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTankLevelTrends control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTankLevelTrends As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTankAlarmHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTankAlarmHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransports As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransportTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransportsInFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportsInFacility As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransportsInFacilityHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportsInFacilityHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransportsUsageReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportsUsageReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAllTransportsReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllTransportsReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransportTrackingReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportTrackingReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divTransportInspectionQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransportInspectionQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnits As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divUserProfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUserProfiles As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAdvancedSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdvancedSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divAbout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAbout As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tblIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblIndex As Global.System.Web.UI.HtmlControls.HtmlTable
End Class
