'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InterfaceTypes

    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ddlInterfaceTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInterfaceTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbxName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxConfigUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxConfigUrl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkShowApplicatorSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowApplicatorSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowBranchSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowBranchSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowBulkProductSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowBulkProductSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowCarrierSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCarrierSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowDriverSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowDriverSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowFacilitySetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowFacilitySetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowOwnerSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowOwnerSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowTankSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTankSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowTransportSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTransportSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowTransportTypeSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTransportTypeSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowUnitSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowUnitSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowInterfaceExchangeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowInterfaceExchangeUnit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkUseInterfaceUnitAsOrderItemUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseInterfaceUnitAsOrderItemUnit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSplitImportedProductsIntoBulkProductOrderItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSplitImportedProductsIntoBulkProductOrderItems As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAllowOrderProductChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowOrderProductChange As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAllowOrderCustomerChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowOrderCustomerChange As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAllowOrderProductGroupingChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowOrderProductGroupingChange As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAllowOrderStatusChangeTicketsExist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowOrderStatusChangeTicketsExist As Global.System.Web.UI.WebControls.CheckBox
End Class
