'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PastOrders

    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ddlFacilityFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFacilityFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPastOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPastOrders As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbxFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxFind As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFind As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cbxIncludeArchived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxIncludeArchived As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnMarkIncomplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMarkIncomplete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnArchive As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUnarchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnarchive As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPrinterFriendly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrinterFriendly As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''orderSummaryFrame control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents orderSummaryFrame As Global.System.Web.UI.HtmlControls.HtmlIframe
End Class
