'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProductSetup
    
    '''<summary>
    '''pnlSelectProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectProduct As Global.KahlerAutomation.TerminalManagement2.SelectProduct
    
    '''<summary>
    '''pnlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduct As Global.KahlerAutomation.TerminalManagement2.Product
    
    '''<summary>
    '''pnlRecipes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecipes As Global.KahlerAutomation.TerminalManagement2.Recipes
    
    '''<summary>
    '''pnlBulkPanelSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBulkPanelSettings As Global.KahlerAutomation.TerminalManagement2.BulkPanelSettings
    
    '''<summary>
    '''pnlInterfaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInterfaces As Global.KahlerAutomation.TerminalManagement2.ProductInterfaces
    
    '''<summary>
    '''pnlBackNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBackNext As Global.KahlerAutomation.TerminalManagement2.BackNextButtons
End Class
