'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StagedOrders
    
    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''PleaseWaitMessagePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleaseWaitMessagePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HiddenButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PleaseWaitPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleaseWaitPopup As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PleaseWaitPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PleaseWaitPanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''SetTareWeightOnTransports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetTareWeightOnTransports As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''ddlStagedOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStagedOrders As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPointOfSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPointOfSale As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrintPickticket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintPickticket As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClearLockedStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearLockedStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSetLockedStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSetLockedStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlGeneralOrderInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGeneralOrderInformation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlOrderDetailStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOrderDetailStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblOrderDetailStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderDetailStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFacility As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlBayAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBayAssigned As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lstUnusedOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUnusedOrders As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnAddOrderToStagedOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddOrderToStagedOrder As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnRemoveOrderFromStagedOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveOrderFromStagedOrder As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tbxFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxFind As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFind As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''litCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCustomerName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rblTicketCreationSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTicketCreationSource As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lstUsedOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUsedOrders As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''chkUseOrderPercents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseOrderPercents As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblOrderPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderPercentage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxOrderPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOrderPercentage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''litPercentageAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPercentageAssigned As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowStagedOrderOrderApplicatorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowStagedOrderOrderApplicatorInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlOrderApplicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrderApplicator As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rowStagedOrderOrderAcresInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowStagedOrderOrderAcresInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbxOrderAcres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxOrderAcres As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShipTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlCustomerSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomerSite As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''litShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litShipTo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ddlCarrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCarrier As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDriver As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''orderDetailsCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orderDetailsCell As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litOrderDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOrderDetails As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlStagedTransports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStagedTransports As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblStagedOrderTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStagedOrderTotals As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rowAutofill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAutofill As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlShortcuts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShortcuts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlUseRemainingOrderQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUseRemainingOrderQuantityShortcut As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnUseRemainingOrderQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseRemainingOrderQuantityShortcut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlUseOriginalOrderQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUseOriginalOrderQuantityShortcut As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnUseOriginalOrderQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseOriginalOrderQuantityShortcut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlUseApplicationRateShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUseApplicationRateShortcut As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnUseApplicationRateShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseApplicationRateShortcut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlUseTransportCapacityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUseTransportCapacityShortcut As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnUseTransportCapacityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseTransportCapacityShortcut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlUseBatchQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUseBatchQuantityShortcut As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnUseBatchQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseBatchQuantityShortcut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlSpecifyTotalQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpecifyTotalQuantityShortcut As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSpecifyTotalQuantityShortcut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpecifyTotalQuantityShortcut As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbxSpecifyTotalQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxSpecifyTotalQuantity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlSpecifyTotalQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSpecifyTotalQuantity As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxNotes As Global.System.Web.UI.WebControls.TextBox
End Class
