'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ticket
    
    '''<summary>
    '''StyleSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StyleSheet As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ticketForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ticketForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''imgLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogo As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''lblTicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTicketNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litTicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTicketNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOrderNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDateTime As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDateTime As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cellPurchaseOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellPurchaseOrderNumber As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblPurchaseOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchaseOrder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litPurchaseOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPurchaseOrderNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cellDischargeLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellDischargeLocation As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''pnlFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFacility As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacility As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litFacility As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlDischargeLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDischargeLocation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDischargeLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDischargeLocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litDischargeLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDischargeLocation As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cellReleaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellReleaseNumber As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblReleaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReleaseNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litReleaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReleaseNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litComments As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlSoldBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSoldBy As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSoldBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoldBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litSoldBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSoldBy As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBranch As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBranch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litBranchLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBranchLocation As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''trOwnerMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOwnerMessage As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''pnlOwnerMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOwnerMessage As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litOwnerMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOwnerMessage As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlSoldTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSoldTo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSoldTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoldTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litSoldTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSoldTo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShipTo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShipTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litShipTo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlAcres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAcres As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAcres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcres As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litAcres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAcres As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''trTicketCustomFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTicketCustomFields As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdTicketCustomFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdTicketCustomFields As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''litProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProducts As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowCarrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCarrier As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblCarrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarrier As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litCarrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCarrier As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowTransport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTransport As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblTransports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransports As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litTransports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTransports As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDriver As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDriver As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDriver As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowUser As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblLoadedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoadedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUser As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowApplicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowApplicator As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblApplicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplicator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litApplicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litApplicator As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowCustomPreLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCustomPreLoadQuestions As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblCustomPreLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomPreLoadQuestions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litCustomPreLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCustomPreLoadQuestions As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowCustomPostLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCustomPostLoadQuestions As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblCustomPostLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomPostLoadQuestions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litCustomPostLoadQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCustomPostLoadQuestions As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rowDisclaimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDisclaimer As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''litDisclaimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDisclaimer As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''BlankSpaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BlankSpaces As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''tdBlank1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBlank1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblBlank1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlank1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdBlank2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBlank2 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblBlank2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlank2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdBlank3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBlank3 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblBlank3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlank3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lineCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lineCell1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lineCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lineCell2 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lineCell3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lineCell3 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''litTicketAddon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTicketAddon As Global.System.Web.UI.WebControls.Literal
End Class
