'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Transports
    
    '''<summary>
    '''main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ddlTransports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlEven control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEven As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tbxName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbxNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTransportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lstRfidNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRfidNumber As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''tbxRfidNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxRfidNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddRfidTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRfidTag As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSetRfidTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSetRfidTag As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRemoveRfidTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveRfidTag As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlTransportUnitId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportUnitId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxEmptyWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxEmptyWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmptyWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmptyWeightUnit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbxMaxWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxMaxWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMaxWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxWeightUnit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbxTempOverweightAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTempOverweightAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTempOverweightAmountUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempOverweightAmountUnit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbxTempOverweightExpirationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTempOverweightExpirationDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tbxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxLength As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlLengthUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLengthUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCarriers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCarriers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCurrentOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrentOrder As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lstCustomFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCustomFields As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlCompartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompartments As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAddCompartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCompartment As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tbxCompartmentCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxCompartmentCapacity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCompartmnetUnitId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompartmnetUnitId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSaveCompartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCompartment As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteCompartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCompartment As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLastInFacilityInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLastInFacilityInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liLastInFacilityLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liLastInFacilityLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblLastInFacilityLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastInFacilityLocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''liLastEnteredFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liLastEnteredFacility As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblLastEnteredFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastEnteredFacility As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''liLastExitedFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liLastExitedFacility As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblLastExitedFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastExitedFacility As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''liLastInFacilityStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liLastInFacilityStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblLastInFacilityStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastInFacilityStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnClearLastInFacilityStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearLastInFacilityStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlInterfaceSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInterfaceSetup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlTransportInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportInterface As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlInterfaceSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInterfaceSettings As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInterface As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbxInterfaceCrossReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxInterfaceCrossReference As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkDefaultSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDefaultSetting As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkExportOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExportOnly As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSaveInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveInterface As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRemoveInterface control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveInterface As Global.System.Web.UI.WebControls.Button
End Class
